# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9550eb97d70d8aa179647a73f8624bb977b0074393adbe7e7e4f1e0af27b16a009c462b9eefc3b90da2d6a94a3561a56c80b1471685a28036144e357a6ebd098

test:
  secret_key_base: 29a7891efacdd834a15b49448127ad2bf1b67015f88675c99245d56e9f3ee8e9454ba75d97f77779702365c306715c0f444aacb87517ba253f2bcbabf832ed35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
